server:
  port: 6374
  context-path: /api

spring:
  # DataSource 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.13.11.22:3306/clou_cj_yun?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: clou_cj_user
    password: ENC(m3lAKYMSjVB5c2kNHiisVcYFschM1vjlVAuJ2rNfRQs=)
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        usemicroServerPrepStmts: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    pool:
      max-active: -1
      max-idle: 100
    port: 6379
    timeout: 0
